### ISSUE TITLE
Firefox Syncにおける設定項目の項目ずれ

### ISSUE THREAD

**Issue by karakufire** [Floorp-Projects/Floorp-dev#5]
## 発生した現象
FirefoxとFloorpとの間において、Firefox Syncを用いて設定の同期を行ったところ、Floorpの「同時に複数のタブを閉じる前に確認する」の有効・無効の設定が、Firefoxでは同名の項目ではなく「前回のウィンドウとタブを開く」の有効・無効の設定と同期する。
![image](https://user-images.githubusercontent.com/10906521/162586208-06e6cea2-06de-4698-be65-d086391f2dd9.png)

また、上級者向けの設定から`services.sync.prefs.sync.browser.sessionstore.resume_session_once`を`false`に設定したが、解決しなかった。

## 環境
Windows 10 ビルド21H1
Floorp 8.6.2
Firefox 99.0

追伸: Twitterにて報告済みですが、ここにまとめを兼ねて報告します。

**Comment by surapunoyousei** [comment]
このバグは Firefox との同期の互換性に干渉しているため、以下の設定を同期しないようにすることで解決すると考えられます。

pref("services.sync.prefs.sync.browser.startup.page", false, locked); 
pref("services.sync.prefs.sync.browser.tabs.warnOnClose", false, locked); 

上記のコードを設定に組み込んだのでもう発生しないはずです。変更される可能性がありますが、リリース予定は4月後半です。ベータ版にはすぐ実装されます。

**Comment by surapunoyousei** [comment]
https://github.com/Floorp-Projects/Floorp-dev/commit/1f66e56653d65e6a42a1f001f36a10c7c94b9c0c
