### ISSUE TITLE
ヘルプのFloorpについての文を変更したほうがよろしいのでは？

### ISSUE THREAD

**Issue by kinoko2k** [Floorp-Projects/Floorp-dev#9]
https://gyazo.com/9163662526149730bac32061a93f6097
のようなssの通りMozilla表示になっているのでFloorpに変更したほうがいいのでは？

**Comment by surapunoyousei** [comment]
言語パックは毎回全部ひとつずつ手動で20言語アップデートしているので毎回きれいに確実にするのはほぼ無理なので、あまり気にしないでください。ひとつづつ丁寧にやっていたらいずれ死んでしまうので、ミスってたらあーやってんなぁ程度でお願いします。

報告ありがとうございます！修正します！
